--georgia

--Start location change
INSERT OR REPLACE INTO StartBiasTerrains(CivilizationType, TerrainType, Tier) VALUES
('CIVILIZATION_GEORGIA', 'TERRAIN_GRASS_HILLS', 2),
('CIVILIZATION_GEORGIA', 'TERRAIN_PLAINS_HILLS', 2);

--TSIKHE Yield 2 cluture, double if golden age
INSERT OR REPLACE INTO Building_YieldChanges(BuildingType, YieldType, YieldChange) VALUES 
('BUILDING_TSIKHE', 'YIELD_CULTURE', '2');
INSERT INTO BuildingModifiers(BuildingType, ModifierId) VALUES 
('BUILDING_TSIKHE', 'TSIKHE_CULTURE_GOLDEN_AGE');

--technologys automatically grant cities walls
INSERT OR REPLACE INTO Types(Type, Kind) VALUES
('MODIFIER_PLAYER_CITIES_GRANT_BUILDING_IN_CITY_IGNORE', 'KIND_MODIFIER');
INSERT INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES	
('MODIFIER_PLAYER_CITIES_GRANT_BUILDING_IN_CITY_IGNORE', 'COLLECTION_PLAYER_CITIES','EFFECT_GRANT_BUILDING_IN_CITY_IGNORE');

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS', 'GOLDEN_AGE_QUESTS_GRANT_TECH_MASONRY_BOOST'),

('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS', 'GOLDEN_AGE_QUESTS_MASONRY_GRANT_CITIES_WALLS'),
('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS', 'GOLDEN_AGE_QUESTS_CASTLES_GRANT_CITIES_WALLS'),
('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS', 'GOLDEN_AGE_QUESTS_CASTLES_GRANT_CITIES_CASTLE'),
('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS', 'GOLDEN_AGE_QUESTS_SIEGE_TACTICS_GRANT_CITIES_WALLS'),
('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS', 'GOLDEN_AGE_QUESTS_SIEGE_TACTICS_GRANT_CITIES_CASTLE'),
('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS', 'GOLDEN_AGE_QUESTS_SIEGE_TACTICS_GRANT_CITIES_TSIKHE');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('TSIKHE_CULTURE_GOLDEN_AGE', 'MODIFIER_BUILDING_YIELD_CHANGE', 0, 0, 0, 'PLAYER_HAS_GOLDEN_AGE', NULL),

('GOLDEN_AGE_QUESTS_GRANT_TECH_MASONRY_BOOST', 'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST', 0, 0, 0, NULL, NULL),

('GOLDEN_AGE_QUESTS_MASONRY_GRANT_CITIES_WALLS', 'MODIFIER_PLAYER_CITIES_GRANT_BUILDING_IN_CITY_IGNORE', 0, 0, 0, NULL, 'REQUIREMENT_PLAYER_HAS_TECH_MASONRY'),
('GOLDEN_AGE_QUESTS_CASTLES_GRANT_CITIES_WALLS', 'MODIFIER_PLAYER_CITIES_GRANT_BUILDING_IN_CITY_IGNORE', 0, 0, 0, NULL, 'REQUIREMENT_PLAYER_HAS_TECH_CASTLES'),
('GOLDEN_AGE_QUESTS_CASTLES_GRANT_CITIES_CASTLE', 'MODIFIER_PLAYER_CITIES_GRANT_BUILDING_IN_CITY_IGNORE', 0, 0, 0, NULL, 'REQUIREMENT_PLAYER_HAS_TECH_CASTLES'),
('GOLDEN_AGE_QUESTS_SIEGE_TACTICS_GRANT_CITIES_WALLS', 'MODIFIER_PLAYER_CITIES_GRANT_BUILDING_IN_CITY_IGNORE', 0, 0, 0, NULL, 'REQUIREMENT_PLAYER_HAS_TECH_SIEGE_TACTICS'),
('GOLDEN_AGE_QUESTS_SIEGE_TACTICS_GRANT_CITIES_CASTLE', 'MODIFIER_PLAYER_CITIES_GRANT_BUILDING_IN_CITY_IGNORE', 0, 0, 0, NULL, 'REQUIREMENT_PLAYER_HAS_TECH_SIEGE_TACTICS'),
('GOLDEN_AGE_QUESTS_SIEGE_TACTICS_GRANT_CITIES_TSIKHE', 'MODIFIER_PLAYER_CITIES_GRANT_BUILDING_IN_CITY_IGNORE', 0, 0, 0, NULL, 'REQUIREMENT_PLAYER_HAS_TECH_SIEGE_TACTICS');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('TSIKHE_CULTURE_GOLDEN_AGE', 'BuildingType', 'BUILDING_TSIKHE'),
('TSIKHE_CULTURE_GOLDEN_AGE', 'Amount', '2'),
('TSIKHE_CULTURE_GOLDEN_AGE', 'YieldType', 'YIELD_CULTURE'),

('GOLDEN_AGE_QUESTS_GRANT_TECH_MASONRY_BOOST', 'TechType', 'TECH_MASONRY'),

('GOLDEN_AGE_QUESTS_MASONRY_GRANT_CITIES_WALLS', 'BuildingType', 'BUILDING_WALLS'),
('GOLDEN_AGE_QUESTS_CASTLES_GRANT_CITIES_WALLS', 'BuildingType', 'BUILDING_WALLS'),
('GOLDEN_AGE_QUESTS_CASTLES_GRANT_CITIES_CASTLE', 'BuildingType', 'BUILDING_CASTLE'),
('GOLDEN_AGE_QUESTS_SIEGE_TACTICS_GRANT_CITIES_WALLS', 'BuildingType', 'BUILDING_WALLS'),
('GOLDEN_AGE_QUESTS_SIEGE_TACTICS_GRANT_CITIES_CASTLE', 'BuildingType', 'BUILDING_CASTLE'),
('GOLDEN_AGE_QUESTS_SIEGE_TACTICS_GRANT_CITIES_TSIKHE', 'BuildingType', 'BUILDING_TSIKHE');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('REQUIREMENT_PLAYER_HAS_TECH_MASONRY', 'REQUIREMENTSET_TEST_ALL'),
('REQUIREMENT_PLAYER_HAS_TECH_CASTLES', 'REQUIREMENTSET_TEST_ALL'),
('REQUIREMENT_PLAYER_HAS_TECH_SIEGE_TACTICS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('REQUIREMENT_PLAYER_HAS_TECH_MASONRY', 'PLAYER_HAS_TECH_MASONRY'),
('REQUIREMENT_PLAYER_HAS_TECH_CASTLES', 'PLAYER_HAS_TECH_CASTLES'),
('REQUIREMENT_PLAYER_HAS_TECH_SIEGE_TACTICS', 'PLAYER_HAS_TECH_SIEGE_TACTICS');

INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('PLAYER_HAS_TECH_MASONRY', 'REQUIREMENT_PLAYER_HAS_TECHNOLOGY'),
('PLAYER_HAS_TECH_CASTLES', 'REQUIREMENT_PLAYER_HAS_TECHNOLOGY'),
('PLAYER_HAS_TECH_SIEGE_TACTICS', 'REQUIREMENT_PLAYER_HAS_TECHNOLOGY');

INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('PLAYER_HAS_TECH_MASONRY', 'TechnologyType', 'TECH_MASONRY'),
('PLAYER_HAS_TECH_CASTLES', 'TechnologyType', 'TECH_CASTLES'),
('PLAYER_HAS_TECH_SIEGE_TACTICS', 'TechnologyType', 'TECH_SIEGE_TACTICS');

-- UA (hd)
-- insert or replace into TraitModifiers
-- 	(TraitType,									ModifierId)
-- select
-- 	'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS',	'TRAIT_GOLDEN_AGE_WILDCARD_SLOT'
-- where exists (select TraitType from Traits where TraitType = 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS');

insert or replace into TraitModifiers
	(TraitType,									ModifierId)
select
	'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS',	'TRAIT_GOLDEN_AGE_UNLOCK_DARK_POLICIES'
where exists (select TraitType from Traits where TraitType = 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS');

insert or ignore into Modifiers
    (ModifierId,                            	ModifierType,												Permanent,	SubjectRequirementSetId,	SubjectStackLimit)
values
    ('TRAIT_GOLDEN_AGE_WILDCARD_SLOT',			'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',	1,			'PLAYER_HAS_GOLDEN_AGE',	1),
	('TRAIT_GOLDEN_AGE_UNLOCK_DARK_POLICIES',	'MODIFIER_PLAYER_ADJUST_PROPERTY',							0,			'PLAYER_HAS_GOLDEN_AGE',	NULL);

insert or ignore into ModifierArguments
    (ModifierId,                            	Name,          			 Value)
values
    ('TRAIT_GOLDEN_AGE_WILDCARD_SLOT',			'GovernmentSlotType',	'SLOT_WILDCARD'),
	('TRAIT_GOLDEN_AGE_UNLOCK_DARK_POLICIES',	'Key',					'CanSlotDarkPolicies'),
	('TRAIT_GOLDEN_AGE_UNLOCK_DARK_POLICIES',	'Amount',				1);



UPDATE Traits SET Description = 'LOC_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_DESCRIPTION_ZJ' WHERE TraitType = 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS';
UPDATE Building SET Description = 'LOC_BUILDING_TSIKHE_DESCRIPTION_XP2_ZJ' WHERE BuildingType = 'BUILDING_TSIKHE';