INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_CIVILIZATION_SATRAPIES', 'PAIRIDAEZA_GOVERNOR_POINTS'),
('TRAIT_CIVILIZATION_SATRAPIES', 'TRAIT_TRADE_CULTURE_FROM_PAIRIDAEZA');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('TRAIT_TRADE_CULTURE_FROM_PAIRIDAEZA', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_PER_IMPROVEMENT_IN_TARGET', 0, 0, 0, NULL, NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('TRAIT_TRADE_CULTURE_FROM_PAIRIDAEZA', 'Amount', '1'), 
('TRAIT_TRADE_CULTURE_FROM_PAIRIDAEZA', 'ImprovementType', 'IMPROVEMENT_PAIRIDAEZA'), 
('TRAIT_TRADE_CULTURE_FROM_PAIRIDAEZA', 'Origin', 'true'), 
('TRAIT_TRADE_CULTURE_FROM_PAIRIDAEZA', 'YieldType', 'YIELD_CULTURE');

INSERT OR REPLACE INTO Improvement_ValidFeatures(ImprovementType, FeatureType)VALUES
('IMPROVEMENT_PAIRIDAEZA', 'FEATURE_FLOODPLAINS'),
('IMPROVEMENT_PAIRIDAEZA', 'FEATURE_FLOODPLAINS_GRASSLAND'),
('IMPROVEMENT_PAIRIDAEZA', 'FEATURE_FLOODPLAINS_PLAINS');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('PAIRIDAEZA_GOVERNOR_POINTS', 'MODIFIER_PLAYER_ADJUST_GOVERNOR_POINTS', 0, 1, 0, NULL, 'PLAYER_HAS_PAIRIDAEZA');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('PAIRIDAEZA_GOVERNOR_POINTS', 'Delta', '1');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('PLAYER_HAS_PAIRIDAEZA', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('PLAYER_HAS_PAIRIDAEZA', 'REQUIRES_PLAYER_HAS_PAIRIDAEZA');
INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('REQUIRES_PLAYER_HAS_PAIRIDAEZA', 'REQUIREMENT_PLAYER_HAS_IMPROVEMENT');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('REQUIRES_PLAYER_HAS_PAIRIDAEZA', 'ImprovementType', 'IMPROVEMENT_PAIRIDAEZA');

UPDATE Traits SET Description = 'LOC_TRAIT_CIVILIZATION_SATRAPIES_DESCRIPTION_ZJ' WHERE TraitType = 'TRAIT_CIVILIZATION_SATRAPIES';
UPDATE Improvements SET Description = 'LOC_IMPROVEMENT_PAIRIDAEZA_DESCRIPTION_ZJ' WHERE ImprovementType = 'IMPROVEMENT_PAIRIDAEZA';