INSERT INTO Building_YieldChanges (BuildingType, YieldType, YieldChange) VALUES
('BUILDING_SUKIENNICE', 'YIELD_PRODUCTION', '2');

--varsion 1: faith
UPDATE Traits SET Description = 'LOC_TRAIT_CIVILIZATION_GOLDEN_LIBERTY_DESCRIPTION_V1_ZJ' WHERE TraitType = 'TRAIT_CIVILIZATION_GOLDEN_LIBERTY';
UPDATE Buildings SET Description = 'LOC_BUILDING_SUKIENNICE_DESCRIPTION_ZJ' WHERE BuildingType='BUILDING_SUKIENNICE';

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_CIVILIZATION_GOLDEN_LIBERTY', 'TRAIT_GOLDEN_LIBERTY_PURCHASE_CIVILIAN');

INSERT OR REPLACE INTO Building_YieldDistrictCopies (BuildingType, OldYieldType, NewYieldType) VALUES
('BUILDING_SUKIENNICE', 'YIELD_GOLD', 'YIELD_FAITH');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('TRAIT_GOLDEN_LIBERTY_PURCHASE_CIVILIAN', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE', 0, 0, 0, NULL, NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('TRAIT_GOLDEN_LIBERTY_PURCHASE_CIVILIAN', 'Tag', 'CLASS_LANDCIVILIAN');


--varsion 2: Population
UPDATE Traits SET Description = 'LOC_TRAIT_CIVILIZATION_GOLDEN_LIBERTY_DESCRIPTION_V2_ZJ' WHERE TraitType = 'TRAIT_CIVILIZATION_GOLDEN_LIBERTY';

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
('TRAIT_CIVILIZATION_GOLDEN_LIBERTY', 'TRAIT_GOLDEN_LIBERTY_DISTRICTS_PLAINS_HOUSING'),
('TRAIT_CIVILIZATION_GOLDEN_LIBERTY', 'TRAIT_GOLDEN_LIBERTY_DISTRICTS_PLAINS_POPULATION');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('TRAIT_GOLDEN_LIBERTY_DISTRICTS_PLAINS_HOUSING', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_HOUSING', 0, 0, 0, NULL, 'REQUIREMENTS_PLOT_IS_NOT_HILLS'),
('TRAIT_GOLDEN_LIBERTY_DISTRICTS_PLAINS_POPULATION', 'MODIFIER_PLAYER_BUILT_CITIES_GRANT_FREE_POPULATION', 0, 0, 0, NULL, 'REQUIREMENTS_PLOT_IS_NOT_HILLS');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('TRAIT_GOLDEN_LIBERTY_DISTRICTS_PLAINS_HOUSING', 'Amount', '1'),
('TRAIT_GOLDEN_LIBERTY_DISTRICTS_PLAINS_POPULATION', 'Amount', '1');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('REQUIREMENTS_PLOT_IS_NOT_HILLS', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('REQUIREMENTS_PLOT_IS_NOT_HILLS', 'PLOT_IS_NOT_HILLS_REQUIREMENT');

INSERT INTO Requirements (RequirementId, RequirementType, Inverse) VALUES 
('PLOT_IS_NOT_HILLS_REQUIREMENT', 'REQUIREMENT_PLOT_IS_HILLS', 1);