-- UPDATE Units
--     SET BaseMoves=5
--     WHERE UnitType='UNIT_SETTLER';

-- --Water Mill compatible
-- UPDATE Modifier
--     SET SubjectRequirementSetId ='PLOT_HAS_PASTURE_INDUSTRY_CORPORATION_REQUIREMENTS'
--     WHERE ModifierId='WATERMILL_ADDPASTURERODUCTION';

-- INSERT INTO Requirements (RequirementId, RequirementType) VALUES	
-- ('REQUIRES_PLOT_HAS_INDUSTRY', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
-- ('REQUIRES_PLOT_HAS_CORPORATION', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES');
-- INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 	
-- ('REQUIRES_PLOT_HAS_INDUSTRY', 'ImprovementType', 'IMPROVEMENT_INDUSTRY'),
-- ('REQUIRES_PLOT_HAS_CORPORATION', 'ImprovementType', 'IMPROVEMENT_CORPORATION');
-- INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
-- ('PLOT_HAS_PASTURE_INDUSTRY_CORPORATION_REQUIREMENTS', 'REQUIREMENTSET_TEST_ANY');	
-- INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
-- ('PLOT_HAS_PASTURE_INDUSTRY_CORPORATION_REQUIREMENTS', 'REQUIRES_PLOT_HAS_PASTURE'),
-- ('PLOT_HAS_PASTURE_INDUSTRY_CORPORATION_REQUIREMENTS','REQUIRES_PLOT_HAS_INDUSTRY'),
-- ('PLOT_HAS_PASTURE_INDUSTRY_CORPORATION_REQUIREMENTS','REQUIRES_PLOT_HAS_CORPORATION');

