UPDATE Beliefs SET Description='LOC_BELIEF_ZEN_MEDITATION_DESCRIPTION_ZJ' WHERE BeliefType='BELIEF_ZEN_MEDITATION';

INSERT OR REPLACE INTO BeliefModifiers (BeliefType, ModifierId) VALUES 
('BELIEF_ZEN_MEDITATION','ZEN_MEDITATION_ADJACENCY_SCIENCE_2');

INSERT INTO GreatPersonIndividualActionModifiers (GreatPersonIndividualType, ModifierId, AttachmentTargetType) VALUES
('GREAT_PERSON_INDIVIDUAL_HILDEGARD_OF_BINGEN', 'GREATPERSON_HOLY_SITE_ADJACENCY_AS_PRODUCTION', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('ZEN_MEDITATION_ADJACENCY_SCIENCE_2', 'MODIFIER_ALL_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS', 0, 0, 0, NULL, 'ZEN_MEDITATION_ADJACENCY_SCIENCE_REQUIREMENTS'),
('GREATPERSON_HOLY_SITE_ADJACENCY_AS_PRODUCTION', 'MODIFIER_PLAYER_DISTRICT_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS', 1, 0, 1, NULL, NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('ZEN_MEDITATION_ADJACENCY_SCIENCE_2', 'YieldTypeToMirror', 'YIELD_FAITH'),
('ZEN_MEDITATION_ADJACENCY_SCIENCE_2', 'YieldTypeToGrant', 'YIELD_SCIENCE'),
('GREATPERSON_HOLY_SITE_ADJACENCY_AS_PRODUCTION', 'YieldTypeToMirror', 'YIELD_FAITH'),
('GREATPERSON_HOLY_SITE_ADJACENCY_AS_PRODUCTION', 'YieldTypeToGrant', 'YIELD_PRODUCTION');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('ZEN_MEDITATION_ADJACENCY_SCIENCE_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('ZEN_MEDITATION_ADJACENCY_SCIENCE_REQUIREMENTS', 'REQUIRES_ZEN_MEDITATION_DISTRICT_IS_HOLY_SITE');
INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('REQUIRES_ZEN_MEDITATION_DISTRICT_IS_HOLY_SITE', 'REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('REQUIRES_ZEN_MEDITATION_DISTRICT_IS_HOLY_SITE', 'DistrictType', 'DISTRICT_HOLY_SITE');