INSERT INTO BeliefModifiers (BeliefType, ModifierId) VALUES 
('BELIEF_PAPAL_PRIMACY', 'PAPAL_PRIMACY_RELIGION_UNIT_NEGATIVE_COMBAT_MODIFIER');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('PAPAL_PRIMACY_RELIGION_UNIT_NEGATIVE_COMBAT', 'MODIFIER_ALL_UNITS_ATTACH_MODIFIER', 0, 0, 0, NULL, 'UNIT_IS_RELIGIOUS'),
('PAPAL_PRIMACY_RELIGION_UNIT_NEGATIVE_COMBAT_MODIFIER', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 0, 0, 0, NULL, 'UNIT_IS_RELIGIOUS');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('PAPAL_PRIMACY_RELIGION_UNIT_NEGATIVE_COMBAT', 'ModifierId', 'PAPAL_PRIMACY_RELIGION_UNIT_NEGATIVE_COMBAT_MODIFIER'),
('PAPAL_PRIMACY_RELIGION_UNIT_NEGATIVE_COMBAT_MODIFIER', 'Amount', '-4');


UPDATE Beliefs SET Description = 'LOC_BELIEF_PAPAL_PRIMACY_DESCRIPTION_ZJ' WHERE BeliefType = 'BELIEF_PAPAL_PRIMACY';