-- GameData1
-- Author: zjhao
-- DateCreated: 4/29/2022 6:31:48 PM
--------------------------------------------------------------
--1.STONE CIRCLES
INSERT INTO BeliefModifiers (BeliefType, ModifierId) VALUES 
('BELIEF_STONE_CIRCLES', 'STONE_CIRCLES_QUARRY_CULTURE');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('STONE_CIRCLES_QUARRY_CULTURE', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 0, NULL, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
('STONE_CIRCLES_QUARRY_CULTURE_MODIFIER', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', 0, 0, 0, NULL, 'PLOT_HAS_QUARRY_REQUIREMENTS');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('STONE_CIRCLES_QUARRY_CULTURE', 'ModifierId', 'STONE_CIRCLES_QUARRY_CULTURE_MODIFIER'),
('STONE_CIRCLES_QUARRY_CULTURE_MODIFIER', 'Amount', 1),
('STONE_CIRCLES_QUARRY_CULTURE_MODIFIER', 'YieldType', 'YIELD_CULTURE');

--2.GODDESS_OF_FIRE give one more SCIENCE
INSERT INTO BeliefModifiers (BeliefType,ModifierID) VALUES	
('BELIEF_GODDESS_OF_FIRE','GODDESS_OF_FIRE_FEATURES_SCIENCE');
INSERT INTO Modifiers (ModifierId,ModifierType,SubjectRequirementSetId) VALUES	
('GODDESS_OF_FIRE_FEATURES_SCIENCE','MODIFIER_ALL_CITIES_ATTACH_MODIFIER','CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
('GODDESS_OF_FIRE_FEATURES_SCIENCE_MODIFIER','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD','PLOT_HAS_GODDES_FIRE_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId,Name,Value) VALUES	
('GODDESS_OF_FIRE_FEATURES_SCIENCE','ModifierId','GODDESS_OF_FIRE_FEATURES_SCIENCE_MODIFIER'),
('GODDESS_OF_FIRE_FEATURES_SCIENCE_MODIFIER','YieldType','YIELD_SCIENCE'),
('GODDESS_OF_FIRE_FEATURES_SCIENCE_MODIFIER','Amount',1);

-- 3.Religions idols give 4 gold
UPDATE ModifierArguments SET Value='4' WHERE ModifierId='RELIGIOUS_IDOLS_BONUS_MINE_FAITH_MODIFIER' AND Name='Amount';
UPDATE ModifierArguments SET Value='YIELD_GOLD' WHERE ModifierId='RELIGIOUS_IDOLS_BONUS_MINE_FAITH_MODIFIER' AND Name='YieldType';
UPDATE ModifierArguments SET Value='4' WHERE ModifierId='RELIGIOUS_IDOLS_LUXURY_MINE_FAITH_MODIFIER' AND Name='Amount';
UPDATE ModifierArguments SET Value='YIELD_GOLD' WHERE ModifierId='RELIGIOUS_IDOLS_LUXURY_MINE_FAITH_MODIFIER' AND Name='YieldType';


--4.CITY_PATRON_GODDESS +50% DISTRICT PRODUCTION
UPDATE ModifierArguments SET Value = 50 WHERE ModifierId = 'CITY_PATRON_GODDESS_DISTRICT_PRODUCTION_MODIFIER';

--5.EARTH_GODDESS +2 faith
UPDATE ModifierArguments SET Value = 2 WHERE ModifierId = 'EARTH_GODDESS_APPEAL_FAITH_MODIFIER' AND Name='Amount';

--6.Fertility Rites Builder faster move
INSERT OR REPLACE INTO BeliefModifiers (BeliefType, ModifierId) VALUES
('BELIEF_FERTILITY_RITES', 'FERTILITY_RITES_BUILDER_MOVEMENT');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('FERTILITY_RITES_BUILDER_MOVEMENT', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', 0, 0, 0, NULL, 'PLAYER_HAS_PANTHEON_REQUIREMENTS'),
('FERTILITY_RITES_BUILDER_MOVEMENT_MODIFIER', 'MODIFIER_PLAYER_UNITS_ADJUST_FRIENDLY_TERRITORY_START_MOVEMENT', 0, 0, 0, NULL, 'UNIT_IS_BUILDER');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('FERTILITY_RITES_BUILDER_MOVEMENT', 'ModifierId', 'FERTILITY_RITES_BUILDER_MOVEMENT_MODIFIER'),
('FERTILITY_RITES_BUILDER_MOVEMENT_MODIFIER', 'Amount', '2');


UPDATE Beliefs SET Description = 'LOC_BELIEF_STONE_CIRCLES_DESCRIPTION_ZJ' WHERE BeliefType = 'BELIEF_STONE_CIRCLES';
UPDATE Beliefs SET Description = 'LOC_BELIEF_GODDESS_OF_FIRE_DESCRIPTION_ZJ' WHERE BeliefType = 'BELIEF_GODDESS_OF_FIRE';
UPDATE Beliefs SET Description = 'LOC_BELIEF_RELIGIOUS_IDOLS_DESCRIPTION_ZJ' WHERE BeliefType = 'BELIEF_RELIGIOUS_IDOLS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_EARTH_GODDESS_EXPANSION2_DESCRIPTION_ZJ' WHERE BeliefType = 'BELIEF_EARTH_GODDESS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_CITY_PATRON_GODDESS_DESCRIPTION_ZJ' WHERE BeliefType = 'BELIEF_CITY_PATRON_GODDESS';
UPDATE Beliefs SET Description = 'LOC_BELIEF_FERTILITY_RITES_DESCRIPTION_ZJ' WHERE BeliefType = 'BELIEF_FERTILITY_RITES';
