UPDATE Buildings SET Description = 'LOC_BUILDING_DAR_E_MEHR_DESCRIPTION_ZJ' WHERE BuildingType = 'BUILDING_DAR_E_MEHR';
UPDATE Beliefs SET Description = 'LOC_BELIEF_DAR_E_MEHR_DESCRIPTION_ZJ' WHERE BeliefType = 'BELIEF_DAR_E_MEHR';

UPDATE Building_YieldsPerEra
    SET YieldChange = 2
    WHERE BuildingType='BUILDING_DAR_E_MEHR' AND YieldType='YIELD_FAITH';

UPDATE Buildings SET Cost = 160 WHERE Cost = 190 AND PrereqDistrict = 'DISTRICT_HOLY_SITE';

INSERT OR REPLACE INTO Building_YieldChanges (BuildingType, YieldType, YieldChange) VALUES
('BUILDING_TEMPLE', 'YIELD_FAITH', 4),
('BUILDING_CATHEDRAL', 'YIELD_FAITH', 4),
('BUILDING_DAR_E_MEHR', 'YIELD_FAITH', 4),
('BUILDING_GURDWARA', 'YIELD_FAITH', 4),
('BUILDING_MEETING_HOUSE', 'YIELD_FAITH', 4),
('BUILDING_MOSQUE', 'YIELD_FAITH', 4),
('BUILDING_PAGODA', 'YIELD_FAITH', 4),
('BUILDING_STUPA', 'YIELD_FAITH', 4),
('BUILDING_WAT', 'YIELD_FAITH', 4),
('BUILDING_SYNAGOGUE', 'YIELD_FAITH', 6);

