--Caguana: Batey provide more culture
-- UPDATE Improvements SET Description = 'LOC_IMPROVEMENT_BATEY_DESCRIPTION_ZJ' WHERE BuildingType = 'IMPROVEMENT_BATEY';
-- UPDATE Improvement_YieldChanges
--     SET YieldChange=2
--     WHERE ImprovementType = 'IMPROVEMENT_BATEY';

--
UPDATE Technologies SET Description='LOC_TECH_BUTTRESS_DESCRIPTION_ZJ' WHERE TechnologyType='TECH_BUTTRESS';

--Improvements can be built on features
REPLACE INTO Improvement_ValidFeatures (ImprovementType, FeatureType, PrereqTech, PrereqCivic) VALUES 
('IMPROVEMENT_MAHAVIHARA', 'FEATURE_FLOODPLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MAHAVIHARA', 'FEATURE_FLOODPLAINS_GRASSLAND', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MAHAVIHARA', 'FEATURE_FLOODPLAINS_PLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MOAI', 'FEATURE_FLOODPLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MOAI', 'FEATURE_FLOODPLAINS_GRASSLAND', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MOAI', 'FEATURE_FLOODPLAINS_PLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MONASTERY', 'FEATURE_FLOODPLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MONASTERY', 'FEATURE_FLOODPLAINS_GRASSLAND', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MONASTERY', 'FEATURE_FLOODPLAINS_PLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_TRADING_DOME', 'FEATURE_FLOODPLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_TRADING_DOME', 'FEATURE_FLOODPLAINS_GRASSLAND', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_TRADING_DOME', 'FEATURE_FLOODPLAINS_PLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_COLOSSAL_HEAD', 'FEATURE_FOREST', NULL, NULL),
('IMPROVEMENT_COLOSSAL_HEAD', 'FEATURE_JUNGLE', NULL, NULL);