INSERT OR REPLACE INTO EnglishText (Tag, Text) VALUES --Policeis
('LOC_POLICY_MILITARY_RECLAMATION_NAME',
'Military Reclamation'),

('LOC_POLICY_MILITARY_RECLAMATION_DESCRIPTION',
'If at peace, Buildings in Encampment +2 [ICON_Food] Food and +2 [ICON_Production] Production.'),

('LOC_POLICY_PRIMITIVE_COMMUNE_NAME',
'Primitive Commune'),

('LOC_POLICY_PRIMITIVE_COMMUNE_DESCRIPTION',
'+1 [ICON_Food] Food in all cities.'),

('LOC_POLICY_LIBERALISM_DESCRIPTION_ZJ',
'+1 [ICON_Food] Food and +1 [ICON_Production] Production in all cities. +1 [ICON_AMENITIES] Amenity to all cities with at least 2 specialty districts.'),

('LOC_POLICY_TRIBUTE_NAME',
'Tribute'),

('LOC_POLICY_TRIBUTE_DESCRIPTION',
'Receive 50 [ICON_Gold] Gold when you sent a delegation to another player.'),

('LOC_POLICY_URBAN_RENEWAL_NAME',
'Urban Renewal'),

('LOC_POLICY_RELIGIOUS_INDUSTRIALIZATION_NAME',
'Religious Industrialization'),

('LOC_POLICY_SCI_TECH_PROSPERITY_NAME',
'Sci-Tech Prosperity'),

('LOC_POLICY_FOUR_YEAR_PLAN_NAME',
'Four year plan'),

('LOC_POLICY_BREAD_AND_CIRCUSES_NAME',
'Bread and Circuses'),

('LOC_POLICY_RELIGIOUS_INDUSTRIALIZATION_DESCRIPTION',
'Industrial zone buildings can be bought with [ICON_Faith] Faith.'),

('LOC_POLICY_URBAN_RENEWAL_DESCRIPTION',
'+35% [ICON_Production] Production toward City center buildings.'),

('LOC_POLICY_VETERANCY_DESCRIPTION_ZJ',
'+30% [ICON_Production] Production toward Aerodrome districts, Encampment districts, Harbor districts, and buildings for these districts.'),

('LOC_POLICY_FREE_MARKET_DESCRIPTION_ZJ',
'Extra [ICON_Gold] Gold or [ICON_Production] Production from buildings in Commercial Hubs and Harbors: +50% if city [ICON_Citizen] population is 10 or higher, +50% if district has at least +4 adjacency bonus.'),

('LOC_POLICY_RATIONALISM_DESCRIPTION_ZJ',
'Extra [ICON_Science] Science from buildings in Campuses: +50% if city [ICON_Citizen] population is 10 or higher, +50% if district has at least +4 adjacency bonus.'),

('LOC_POLICY_SIMULTANEUM_DESCRIPTION_ZJ',
'Extra [ICON_Faith] Faith from buildings in Holy Sites: +50% if city [ICON_Citizen] population is 10 or higher, +50% if district has at least +4 adjacency bonus.'),

('LOC_POLICY_GRAND_OPERA_DESCRIPTION_ZJ',
'Extra [ICON_Culture] Culture from buildings in Theaters: +50% if city [ICON_Citizen] population is 10 or higher, +50% if district has at least +4 adjacency bonus.'),

('LOC_POLICY_INTEGRATED_SPACE_CELL_DESCRIPTION_ZJ',
'+15% [ICON_Production] Production toward Space Race projects if a city has a Military Academy or a Hangar, or a Seaport.'),

('LOC_POLICY_SCI_TECH_PROSPERITY_DESCRIPTION',
'+100% [ICON_Production] Production toward Campus district or its buildings. But temporarily remove intrinsic [ICON_Science] Science output from Campus buildings.'),

('LOC_POLICY_FOUR_YEAR_PLAN_DESCRIPTION',
"Encampment +1 [ICON_RESOURCE_OIL] Oil once revealed.[NEWLINE]Harbor +1 [ICON_RESOURCE_COAL] Coal once revealed.[NEWLINE]Aerodrome +1 [ICON_RESOURCE_ALUMINUM] Aluminum once revealed."),

('LOC_POLICY_BREAD_AND_CIRCUSES_DESCRIPTION',
'+0.6 [ICON_Culture] Culture per [ICON_Citizen] Citizen, but cities -1 [ICON_AMENITIES] Amenity.');

INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text) VALUES
("zh_Hans_CN",  'LOC_POLICY_MILITARY_RECLAMATION_NAME',
'屯垦戍边'),
("zh_Hans_CN",  'LOC_POLICY_MILITARY_RECLAMATION_DESCRIPTION',
'和平时期，军营内建筑物+2 [ICON_Food] 食物和 +2 [ICON_Production] 生产力。'),
("zh_Hans_CN",  'LOC_POLICY_PRIMITIVE_COMMUNE_NAME',
'原始公社'),
("zh_Hans_CN",  'LOC_POLICY_PRIMITIVE_COMMUNE_DESCRIPTION',
'所有城市+1 [ICON_Food] 食物。'),
("zh_Hans_CN",  'LOC_POLICY_LIBERALISM_DESCRIPTION_ZJ',
'所有城市+1 [ICON_Food] 食物和+1 [ICON_Production] 生产力。拥有至少两个独立区域的所有城市+1 [ICON_AMENITIES] 宜居度。'),
("zh_Hans_CN",  'LOC_POLICY_GIFT_EXCHANGE_NAME',
'朝贡'),
('zh_Hans_CN', 'LOC_POLICY_SCI_TECH_PROSPERITY_NAME',
'科教兴国'),
('zh_Hans_CN', 'LOC_POLICY_FOUR_YEAR_PLAN_NAME',
'四年计划'),
('zh_Hans_CN', 'LOC_POLICY_BREAD_AND_CIRCUSES_NAME',
'面包与马戏'),
("zh_Hans_CN",  'LOC_POLICY_GIFT_EXCHANGE_DESCRIPTION',
'向其他玩家派遣代表团时获得50 [ICON_Gold] 金币。'),
('zh_Hans_CN', 'LOC_POLICY_RELIGIOUS_INDUSTRIALIZATION_NAME',
'宗教工业化'),
('zh_Hans_CN', 'LOC_POLICY_RELIGIOUS_INDUSTRIALIZATION_DESCRIPTION',
'[ICON_Faith] 信仰值可用来购买工业区建筑。'),
("zh_Hans_CN",  'LOC_POLICY_URBAN_RENEWAL_NAME',
'翻新改造'),
("zh_Hans_CN",  'LOC_POLICY_URBAN_RENEWAL_DESCRIPTION',
'建造市中心建筑时+35% [ICON_Production] 生产力。'),
("zh_Hans_CN",  'LOC_POLICY_VETERANCY_DESCRIPTION_ZJ',
'建造军营、港口、航空港和这些区域中的建筑时+30% [ICON_Production] 生产力。'),
('zh_Hans_CN', 'LOC_POLICY_SCI_TECH_PROSPERITY_DESCRIPTION',
'建造学院区域或其中建筑时+100% [ICON_Production] 生产力，但暂时取消学院区建筑固定产出的 [ICON_Science] 科技值。'),
('zh_Hans_CN', 'LOC_POLICY_FOUR_YEAR_PLAN_DESCRIPTION',
"如果战略资源已经解锁，军营 +1 [ICON_RESOURCE_OIL] 石油。[NEWLINE]港口 +1 [ICON_RESOURCE_COAL] 煤。[NEWLINE]航空港 +1 [ICON_RESOURCE_ALUMINUM] 铝。"),
('zh_Hans_CN', 'LOC_POLICY_BREAD_AND_CIRCUSES_DESCRIPTION',
'每位 [ICON_Citizen] 公民将提供0.6点 [ICON_Culture] 文化值，但所有城市-1 [ICON_AMENITIES] 宜居度。');