INSERT OR REPLACE INTO EnglishText (Tag,Text) VALUES --Policeis
('LOC_POLICY_PRIMITIVE_COMMUNE_NAME',
'Primitive Commune'),

('LOC_POLICY_PRIMITIVE_COMMUNE_DESCRIPTION', 
'+1 [ICON_Food] Food in all cities.'),

('LOC_POLICY_LIBERALISM_DESCRIPTION_ZJ', 
'+1 [ICON_Food] Food and +1 [ICON_Production] Production in all cities.'),

('LOC_POLICY_URBAN_RENEWAL_NAME',
'Urban Renewal'),

('LOC_POLICY_URBAN_RENEWAL_DESCRIPTION', 
'+50% [ICON_Production] Production toward City center buildings.'),

('LOC_POLICY_VETERANCY_DESCRIPTION_ZJ',
'+30% [ICON_Production] Production toward Aerodrome districts, Encampment districts, Harbor districts, and buildings for these districts.'),

('LOC_POLICY_INTEGRATED_SPACE_CELL_DESCRIPTION_ZJ',
'+15% [ICON_Production] Production toward Space Race projects if a city has a Military Academy or a Hangar, or a Seaport.'),

('LOC_POLICY_MILITARY_RESEARCH_EXPANSION1_DESCRIPTION_ZJ',
'Military Academies, Seaports, and Renaissance Walls generate +3 [ICON_Science] Science.');