INSERT OR REPLACE INTO EnglishText (Tag,Text) VALUES --Policeis
('LOC_POLICY_MILITARY_RECLAMATION_NAME',
'Military Reclamation'),

('LOC_POLICY_MILITARY_RECLAMATION_DESCRIPTION',
'Buildings in Encampment +2 [ICON_Food] Food and +2 [ICON_Production] Production.'),

('LOC_POLICY_PRIMITIVE_COMMUNE_NAME',
'Primitive Commune'),

('LOC_POLICY_PRIMITIVE_COMMUNE_DESCRIPTION', 
'+1 [ICON_Food] Food in all cities.'),

('LOC_POLICY_LIBERALISM_DESCRIPTION_ZJ', 
'+1 [ICON_Food] Food and +1 [ICON_Production] Production in all cities.'),

('LOC_POLICY_URBAN_RENEWAL_NAME',
'Urban Renewal'),

('LOC_POLICY_URBAN_RENEWAL_DESCRIPTION', 
'+50% [ICON_Production] Production toward City center buildings.'),

('LOC_POLICY_VETERANCY_DESCRIPTION_ZJ',
'+30% [ICON_Production] Production toward Aerodrome districts, Encampment districts, Harbor districts, and buildings for these districts.'),

('LOC_POLICY_FREE_MARKET_DESCRIPTION_ZJ',
'Extra [ICON_Gold] Gold or [ICON_Production] Production from buildings in Commercial Hubs and Harbors: +50% if city [ICON_Citizen] population is 10 or higher, +50% if district has at least +4 adjacency bonus.'),

('LOC_POLICY_RATIONALISM_DESCRIPTION_ZJ',
'Extra [ICON_Science] Science from buildings in Campuses: +50% if city [ICON_Citizen] population is 10 or higher, +50% if district has at least +4 adjacency bonus.'),

('LOC_POLICY_SIMULTANEUM_DESCRIPTION_ZJ',
'Extra [ICON_Faith] Faith from buildings in Holy Sites: +50% if city [ICON_Citizen] population is 10 or higher, +50% if district has at least +4 adjacency bonus.'),

('LOC_POLICY_GRAND_OPERA_DESCRIPTION_ZJ',
'Extra [ICON_Culture] Culture from buildings in Theaters: +50% if city [ICON_Citizen] population is 10 or higher, +50% if district has at least +4 adjacency bonus.'),

('LOC_POLICY_INTEGRATED_SPACE_CELL_DESCRIPTION_ZJ',
'+15% [ICON_Production] Production toward Space Race projects if a city has a Military Academy or a Hangar, or a Seaport.');