UPDATE GreatPersonIndividuals SET BirthEffectTextOverride='MIMAR_SINAN_DESCRIPTION_ZJ' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_MIMAR_SINAN';
UPDATE GreatPersonIndividuals SET BirthEffectTextOverride='COLAEUS_DESCRIPTION_ZJ' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_COLAEUS';
UPDATE GreatPersonIndividuals SET BirthEffectTextOverride='IRENE_OF_ATHENS_DESCRIPTION_ZJ' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_IRENE_OF_ATHENS';

DELETE FROM GreatPersonIndividualActionModifiers WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_COLAEUS' AND ModifierId='GREATPERSON_FAITH_SMALL';
INSERT OR REPLACE INTO GreatPersonIndividualActionModifiers (GreatPersonIndividualType, ModifierId, AttachmentTargetType) VALUES
('GREAT_PERSON_INDIVIDUAL_MIMAR_SINAN', 'GREATPERSON_GOLD_MEDIUM', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_COLAEUS', 'GREATPERSON_DISTRICTS_GOLD_BONUS', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_UNIT_GREATPERSON'),
('GREAT_PERSON_INDIVIDUAL_IRENE_OF_ATHENS', 'GREATPERSON_MARKET_CULTURE', 'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
('GREATPERSON_DISTRICTS_GOLD_BONUS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE', 0, 1, 0, NULL, 'PLOT_IS_OR_ADJACENT_TO_COAST'),
('GREATPERSON_MARKET_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE', 0, 1, 0, NULL, NULL);
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
-- ('GREATPERSON_DOMESTIC_ROUTE_GOLD_PER_SPECIALTY_DISTRICT', 'Amount', '1'),
('GREATPERSON_DISTRICTS_GOLD_BONUS', 'Amount', '2'),
('GREATPERSON_DISTRICTS_GOLD_BONUS', 'YieldType', 'YIELD_GOLD'),
('GREATPERSON_MARKET_CULTURE', 'BuildingType', 'BUILDING_MARKET'),
('GREATPERSON_MARKET_CULTURE', 'Amount', '2'),
('GREATPERSON_MARKET_CULTURE', 'YieldType', 'YIELD_CULTURE');