--Caguana: Batey provide more culture
UPDATE Civilizations SET Description = 'LOC_CIVILIZATION_CAGUANA_DESCRIPTION_ZJ' WHERE CivilizationType = 'CIVILIZATION_CAGUANA';

UPDATE Improvement_YieldChanges SET YieldChange = 2 WHERE ImprovementType = 'IMPROVEMENT_BATEY';

--Preslav: Cities receive +4 Loyalty per building
UPDATE Civilizations SET Description = 'LOC_CIVILIZATION_PRESLAV_DESCRIPTION_ZJ' WHERE CivilizationType = 'CIVILIZATION_PRESLAV';

UPDATE ModifierArguments SET Value = '4' WHERE ModifierId = 'MINOR_CIV_PRESLAV_BARRACKS_STABLE_IDENTITY_BONUS' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = '4' WHERE ModifierId = 'MINOR_CIV_PRESLAV_ARMORY_IDENTITY_BONUS' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = '4' WHERE ModifierId = 'MINOR_CIV_PRESLAV_MILITARY_ACADEMY_IDENTITY_BONUS' AND Name = 'Amount';

--Vilnius: Theater squares give gold base on adjacency bonus
UPDATE Civilizations SET Description = 'LOC_CIVILIZATION_VILNIUS_DESCRIPTION_ZJ' WHERE CivilizationType = 'CIVILIZATION_VILNIUS';

DELETE FROM TraitModifiers WHERE TraitType = 'MINOR_CIV_VILNIUS_TRAIT';
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
('MINOR_CIV_VILNIUS_TRAIT', 'MINOR_CIV_VILNIUS_THEATER_YIELD_GOLD');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
('MINOR_CIV_VILNIUS_THEATER_YIELD_GOLD', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS', 0, 0, 0, NULL, NULL);

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MINOR_CIV_VILNIUS_THEATER_YIELD_GOLD', 'YieldTypeToMirror', 'YIELD_CULTURE'),
('MINOR_CIV_VILNIUS_THEATER_YIELD_GOLD', 'YieldTypeToGrant', 'YIELD_GOLD');

--Improvements can be built on features
REPLACE INTO Improvement_ValidFeatures (ImprovementType, FeatureType, PrereqTech, PrereqCivic) VALUES 
('IMPROVEMENT_MAHAVIHARA', 'FEATURE_FLOODPLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MAHAVIHARA', 'FEATURE_FLOODPLAINS_GRASSLAND', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MAHAVIHARA', 'FEATURE_FLOODPLAINS_PLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MOAI', 'FEATURE_FLOODPLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MOAI', 'FEATURE_FLOODPLAINS_GRASSLAND', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MOAI', 'FEATURE_FLOODPLAINS_PLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MONASTERY', 'FEATURE_FLOODPLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MONASTERY', 'FEATURE_FLOODPLAINS_GRASSLAND', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_MONASTERY', 'FEATURE_FLOODPLAINS_PLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_TRADING_DOME', 'FEATURE_FLOODPLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_TRADING_DOME', 'FEATURE_FLOODPLAINS_GRASSLAND', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_TRADING_DOME', 'FEATURE_FLOODPLAINS_PLAINS', 'TECH_BUTTRESS', NULL),
('IMPROVEMENT_COLOSSAL_HEAD', 'FEATURE_FOREST', NULL, NULL),
('IMPROVEMENT_COLOSSAL_HEAD', 'FEATURE_JUNGLE', NULL, NULL);