UPDATE Traits SET Description = 'LOC_TRAIT_LEADER_CAESAR_DESCRIPTION_ZJ' WHERE TraitType = 'TRAIT_LEADER_CAESAR';

UPDATE RequirementArguments SET Value = 'TECH_IRON_WORKING' WHERE RequirementId = 'REQUIRES_PLAYER_HAS_STEEL';

INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId) VALUES 
-- ('TRAIT_LEADER_CAESAR', 'TRAIT_PALACE_GREAT_GENERAL');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('TRAIT_PALACE_GREAT_GENERAL', 'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS', 0, 0, 0, NULL, 'REQUIREMENT_PLAYER_HAS_CIVIC_CODE_OF_LAWS');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('TRAIT_PALACE_GREAT_GENERAL', 'Amount', '1'),
('TRAIT_PALACE_GREAT_GENERAL', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_GENERAL'),
('TRAIT_CAESAR_GOLD_CAPTURED_CITY_STEEL_MODIFIER', 'Amount', '100'),
('BARBARIAN_CAMP_GOLD_CAPTURED_CITY_STEEL', 'Amount', '100');

-- RequirementSets
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('REQUIREMENT_PLAYER_HAS_CIVIC_CODE_OF_LAWS', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('REQUIREMENT_PLAYER_HAS_CIVIC_CODE_OF_LAWS', 'PLAYER_HAS_CIVIC_CODE_OF_LAWS');

-- Requirements
INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('PLAYER_HAS_CIVIC_CODE_OF_LAWS', 'REQUIREMENT_PLAYER_HAS_CIVIC');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('PLAYER_HAS_CIVIC_CODE_OF_LAWS', 'CivicType', 'CIVIC_CODE_OF_LAWS');