UPDATE Traits SET Description = 'LOC_TRAIT_LEADER_CAESAR_DESCRIPTION_ZJ' WHERE TraitType = 'TRAIT_LEADER_CAESAR';

INSERT OR REPLACE INTO StartBiasResources(CivilizationType, ResourceType, Tier) VALUES
('CIVILIZATION_EGYPT', 'RESOURCE_IRON', 5);

UPDATE Modifiers SET SubjectRequirementSetId = 'PLAYER_HAS_IRON_WORKING_REQUIREMENTS' WHERE ModifierId = 'TRAIT_CAESAR_GOLD_CAPTURED_CITY_STEEL';
UPDATE Modifiers SET SubjectRequirementSetId = 'PLAYER_HAS_IRON_WORKING_REQUIREMENTS' WHERE ModifierId = 'BARBARIAN_CAMP_GOLD_CAPTURED_CITY_STEEL';
UPDATE ModifierArguments SET Value = 150 WHERE ModifierId = 'BARBARIAN_CAMP_GOLD_CAPTURED_CITY_STEEL' AND Name = 'Amount';

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('PLAYER_HAS_IRON_WORKING_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('PLAYER_HAS_IRON_WORKING_REQUIREMENTS', 'REQUIRES_PLAYER_HAS_IRON_WORKING');
INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('REQUIRES_PLAYER_HAS_IRON_WORKING', 'REQUIREMENT_PLAYER_HAS_TECHNOLOGY');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('REQUIRES_PLAYER_HAS_IRON_WORKING', 'TechnologyType', 'TECH_IRON_WORKING');

---------------
-- NEW trait --
---------------

--Type
-- INSERT INTO Types (Type, Kind) VALUES
-- ('ABILITY_CAESAR_GOLD_GOODY', 'KIND_ABILITY');

-- INSERT OR REPLACE INTO UnitAbilites (UnitAbilityType, Description, Inactive) VALUES
-- ('ABILITY_CAESAR_GOLD_GOODY', 'LOC_ABILITY_CAESAR_GOLD_GOODY_DESCRIPTION', 1);
-- INSERT OR REPLACE INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES
-- ('ABILITY_CAESAR_GOLD_GOODY','TRAIT_CAESAR_GOLD_GOODY_MODIFIER');

INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_CAESAR', 'TRAIT_CAESAR_GOLD_GOODY');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES
-- ('TRAIT_CAESAR_GOLD_GOODY', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', 0, 0, 0, NULL, NULL),
('TRAIT_CAESAR_GOLD_GOODY', 'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER', 0, 0, 0, NULL, NULL),
('TRAIT_CAESAR_GOLD_GOODY_MODIFIER', 'MODIFIER_PLAYER_GRANT_YIELD', 0, 0, 0, NULL, 'PLOT_HAS_GOODY_HUT_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
-- ('TRAIT_CAESAR_GOLD_GOODY', 'AbilityType', 'ABILITY_CAESAR_GOLD_GOODY'),
('TRAIT_CAESAR_GOLD_GOODY', 'ModifierId', 'TRAIT_CAESAR_GOLD_GOODY_MODIFIER'),
('TRAIT_CAESAR_GOLD_GOODY_MODIFIER', 'Amount', '100'),
('TRAIT_CAESAR_GOLD_GOODY_MODIFIER', 'YieldType', 'YIELD_GOLD');

--Requirements
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('PLOT_HAS_GOODY_HUT_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('PLOT_HAS_GOODY_HUT_REQUIREMENTS', 'REQUIRES_PLOT_HAS_GOODY_HUT');
INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('REQUIRES_PLOT_HAS_GOODY_HUT', 'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('REQUIRES_PLOT_HAS_GOODY_HUT', 'ImprovementType', 'IMPROVEMENT_GOODY_HUT');

