UPDATE Traits SET Description = 'LOC_TRAIT_LEADER_CAESAR_DESCRIPTION_ZJ' WHERE TraitType = 'TRAIT_LEADER_CAESAR';

UPDATE RequirementArguments SET Value = 'TECH_IRON_WORKING' WHERE RequirementId = 'REQUIRES_PLAYER_HAS_STEEL';

INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId) VALUES 
('TRAIT_LEADER_CAESAR', 'TRAIT_INCREASE_COMBAT_BARBARIAN');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('TRAIT_INCREASE_COMBAT_BARBARIAN', 'MODIFIER_PLAYER_UNITS_ADJUST_BARBARIAN_COMBAT', 0, 0, 0, NULL, NULL);
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('TRAIT_CAESAR_GOLD_CAPTURED_CITY_STEEL_MODIFIER', 'Amount', '200'),
('BARBARIAN_CAMP_GOLD_CAPTURED_CITY_STEEL', 'Amount', '100'),
('TRAIT_INCREASE_COMBAT_BARBARIAN', 'Amount', '4');


-- INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
-- ('PLAYER_HAS_IRON_WORKING_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');
-- INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
-- ('PLAYER_HAS_IRON_WORKING_REQUIREMENTS', 'REQUIRES_PLAYER_HAS_IRON_WORKING');
-- INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
-- ('REQUIRES_PLAYER_HAS_IRON_WORKING', 'REQUIREMENT_PLAYER_HAS_TECHNOLOGY');
-- INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
-- ('REQUIRES_PLAYER_HAS_IRON_WORKING', 'TechnologyType', 'TECH_IRON_WORKING');