INSERT OR REPLACE INTO EnglishText (Tag,Text) VALUES
('LOC_TRAIT_LEADER_SEJONG_DESCRIPTION_ZJ',
'+2 [ICON_Science] Science and +2 [ICON_Culture] Culture from each [ICON_GREATWORK_WRITING] Great Work of Writing. Library provide +1 [ICON_GREATWRITER] Great Writer point. Library +1 slot for [ICON_GREATWORK_WRITING] Great Work of Writing.'),
('LOC_TRAIT_LEADER_SUNDIATA_KEITA_DESCRIPTION_ZJ',
'+2 [ICON_Science] Science (Every time enter Gold Ages or every building in the market of [ICON_TRADEROUTE] Trade Routes start city will increase the number by 2) from international [ICON_TRADEROUTE] Trade Routes.'),
('LOC_TRAIT_LEADER_TOKUGAWA_DESCRIPTION_ZJ',
"Builds Government Plaza districts and its buildings in half the time. International [ICON_TRADEROUTE] Trade Routes receive -25% yields and Tourism [ICON_Tourism] Tourism, but domestic [ICON_TRADEROUTE] Trade Routes gain +1 [ICON_Culture] Culture, +1 [ICON_Science] Science, and +3 [ICON_Gold] Gold for every specialty district at the destination. Cities within 6 tiles of Japan's [ICON_Capital] Capital are 100% loyal and, after researching Flight, gain +1 [ICON_Tourism] Tourism for every specialty district."),
('LOC_TRAIT_LEADER_LINCOLN_DESCRIPTION_ZJ',
'Builds Industrial Zone districts and its buildings in half the time. Industrial Zones give +3 Loyalty per turn, +2 [ICON_Housing] housing, and +2 [ICON_Amenities] Amenity but your Plantations give -2 Loyalty per turn. Receive a free Melee unit after constructing Industrial Zones and their buildings. The free unit does not require resources when created or to maintain and recevices +5 [ICON_Strength] Combat Strength.'),
('LOC_TRAIT_LEADER_CAESAR_DESCRIPTION_ZJ',
'+1 [ICON_GREATGENERAL] Great General point per turn. +200 (becomes +400 after you research Iron Working) [ICON_Gold] Gold whenever you conquer a city for the first time. +100 (becomes +200 after you research Iron Working) [ICON_Gold] Gold when you earn [ICON_Gold] Gold from a Barbarian Outputs. +75 [ICON_Gold] Gold from goodyhunt.');