UPDATE Traits SET Description = 'LOC_TRAIT_CIVILIZATION_BABYLON_DESCRIPTION_ZJ' WHERE TraitType = 'TRAIT_CIVILIZATION_BABYLON';

DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_BABYLON';
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
('TRAIT_CIVILIZATION_BABYLON', 'TRAIT_GRANT_ALL_EUREKA');

INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('TRAIT_GRANT_ALL_EUREKA', 'MODIFIER_PLAYER_GRANT_ALL_TECHNOLOGY_BOOST_BY_ERA', 1, 1, 0, NULL, NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('TRAIT_GRANT_ALL_EUREKA', 'StartEraType', 'ERA_ANCIENT'),
('TRAIT_GRANT_ALL_EUREKA', 'EndEraType', 'ERA_FUTURE');