UPDATE Traits SET Description = 'LOC_TRAIT_CIVILIZATION_DYNASTIC_CYCLE_EXPANSION2_DESCRIPTION_ZJ' WHERE TraitType = 'TRAIT_CIVILIZATION_DYNASTIC_CYCLE';
UPDATE Traits SET Description = 'LOC_TRAIT_LEADER_FIRST_EMPEROR_EXPANSION2_DESCRIPTION_ZJ' WHERE TraitType = 'FIRST_EMPEROR_TRAIT';

UPDATE TraitModifiers SET TraitType = 'FIRST_EMPEROR_TRAIT' WHERE ModifierId IN ('TRAIT_CIVIC_BOOST_WONDER_ERA', 'TRAIT_TECHNOLOGY_BOOST_WONDER_ERA');
UPDATE TraitModifiers SET TraitType = 'TRAIT_CIVILIZATION_DYNASTIC_CYCLE' WHERE ModifierId = 'TRAIT_ADJUST_BUILDER_CHARGES';