
--Start location change
INSERT OR REPLACE INTO StartBiasFeatures(CivilizationType, FeatureType, Tier) VALUES
('CIVILIZATION_EGYPT', 'FEATURE_FLOODPLAINS', 4);

INSERT OR REPLACE INTO StartBiasTerrains(CivilizationType, TerrainType, Tier) VALUES
('CIVILIZATION_EGYPT', 'TERRAIN_DESERT', 1),
('CIVILIZATION_EGYPT', 'TERRAIN_DESERT_HILLS', 1);


--Sphinx buffed
UPDATE Improvement_YieldChanges
    SET YieldChange=2
    WHERE ImprovementType='IMPROVEMENT_SPHINX' AND YieldType='YIELD_FAITH';
UPDATE Improvement_BonusYieldChanges
    SET BonusYieldChange=2
    WHERE ImprovementType='IMPROVEMENT_SPHINX' AND YieldType='YIELD_CULTURE';

INSERT INTO ImprovementModifiers (ImprovementType, ModifierId) VALUES
('IMPROVEMENT_SPHINX', 'SPHINX_WONDERADJACENCY_CULTURE');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('SPHINX_WONDERADJACENCY_CULTURE', 'MODIFIER_SINGLE_PLOT_ADJUST_PLOT_YIELDS', 0, 0, 0, NULL, 'PLOT_ADJACENT_TO_WONDER_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('SPHINX_WONDERADJACENCY_CULTURE', 'YieldType', 'YIELD_CULTURE'),
('SPHINX_WONDERADJACENCY_CULTURE', 'Amount', '1');


--UA: +50% Production to wonders that next to river 
UPDATE ModifierArguments
    SET Value='50'
    WHERE ModifierId='TRAIT_RIVER_FASTER_BUILDTIME_WONDER';
UPDATE ModifierArguments
    SET Value='0'
    WHERE ModifierId='TRAIT_RIVER_FASTER_BUILDTIME_DISTRICT';

--every wonder that before medieval age give +1 TRADE_ROUTE_CAPACITY and a free TRADER
insert into BuildingModifiers (BuildingType,ModifierId)
    select 	BuildingType ,'TRAIT_WONDER_EXTRA_TRADE_ROUTE_CAPACITY_MODIFIER' from Buildings where IsWonder = 1 and ObsoleteEra = 'ERA_MEDIEVAL'; 
insert into BuildingModifiers (BuildingType,ModifierId)
    select 	BuildingType ,'TRAIT_FREE_TRADEER_AFTER_FININSHING_WONDER_MODIFIER' from Buildings where IsWonder = 1 and ObsoleteEra = 'ERA_MEDIEVAL'; 

--QUARRY boost Masonry,  Farm boost Irrigation
INSERT INTO ImprovementModifiers (ImprovementType, ModifierId) VALUES 
('IMPROVEMENT_QUARRY', 'QUARRY_GRANT_TECH_MASONRY_MODIFIER'),
('IMPROVEMENT_FARM', 'FARM_GRANT_TECH_IRRIGATION_MODIFIER');

-- INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
-- ('TRAIT_CIVILIZATION_ITERU', 'TRAIT_WONDER_EXTRA_TRADE_ROUTE_CAPACITY'),
-- ('TRAIT_CIVILIZATION_ITERU', 'TRAIT_FREE_TRADEER_AFTER_FININSHING_WONDER'),
-- ('TRAIT_CIVILIZATION_ITERU', 'FIRST_DISTRICT_GRANT_CIVIC_STATE_WORKFORCE'),
-- ('TRAIT_CIVILIZATION_ITERU', 'QUARRY_GRANT_MASONRY');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
-- ('TRAIT_WONDER_EXTRA_TRADE_ROUTE_CAPACITY', 'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER', 0, 0, 0, NULL, 'THIS_WONDER_IS_ANCIENT_OR_CLASSICAL'),
('TRAIT_WONDER_EXTRA_TRADE_ROUTE_CAPACITY_MODIFIER', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', 1, 0, 0, NULL, 'REQUIREMENTS_PLAYER_IS_EGYPT'),
-- ('TRAIT_FREE_TRADEER_AFTER_FININSHING_WONDER', 'MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER', 0, 0, 0, NULL, 'THIS_WONDER_IS_ANCIENT_OR_CLASSICAL'),
('TRAIT_FREE_TRADEER_AFTER_FININSHING_WONDER_MODIFIER', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_IN_CITY', 1, 0, 0, NULL, 'REQUIREMENTS_PLAYER_IS_EGYPT'),
-- ('FIRST_DISTRICT_GRANT_CIVIC_STATE_WORKFORCE','MODIFIER_ALL_DISTRICTS_ATTACH_MODIFIER', 0, 0, 0, NULL, NULL),
-- ('FIRST_DISTRICT_GRANT_CIVIC_STATE_WORKFORCE_MODIFIER','MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY', 1, 0, 0, NULL, 'EGYPT_REQUIREMENTS'),
-- ('QUARRY_GRANT_MASONRY', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 0, NULL, NULL),
('QUARRY_GRANT_TECH_MASONRY_MODIFIER','MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY', 1, 0, 0, NULL, 'REQUIREMENTS_PLAYER_IS_EGYPT'),
('FARM_GRANT_TECH_IRRIGATION_MODIFIER','MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY', 1, 0, 0, NULL, 'REQUIREMENTS_EGYPT_PLOT_HAS_RESOURCE');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
-- ('TRAIT_WONDER_EXTRA_TRADE_ROUTE_CAPACITY', 'ModifierId'， 'TRAIT_WONDER_EXTRA_TRADE_ROUTE_CAPACITY_MODIFIER'),
('TRAIT_WONDER_EXTRA_TRADE_ROUTE_CAPACITY_MODIFIER', 'Amount', '1'),
-- ('TRAIT_FREE_TRADEER_AFTER_FININSHING_WONDER', 'ModifierId'， 'TRAIT_FREE_TRADEER_AFTER_FININSHING_WONDER_MODIFIER'),
('TRAIT_FREE_TRADEER_AFTER_FININSHING_WONDER_MODIFIER', 'UnitType', 'UNIT_TRADER'),
('TRAIT_FREE_TRADEER_AFTER_FININSHING_WONDER_MODIFIER', 'Amount', '1'),
-- ('QUARRY_GRANT_MASONRY', 'ModifierId'， 'QUARRY_GRANT_MASONRY_MODIFIER'),
('QUARRY_GRANT_TECH_MASONRY_MODIFIER', 'TechType', 'TECH_MASONRY'),
('FARM_GRANT_TECH_IRRIGATION_MODIFIER', 'TechType', 'TECH_IRRIGATION');

INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
('PLAYER_IS_EGYPT', 'REQUIREMENT_PLAYER_TYPE_MATCHES'),
('PLOT_HAS_RESOURCE', 'REQUIREMENT_PLOT_HAS_ANY_RESOURCE');
INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('PLAYER_IS_EGYPT', 'CivilizationType', 'CIVILIZATION_EGYPT');
INSERT INTO RequirementSets (RequirementSetId,RequirementSetType) values
('REQUIREMENTS_PLAYER_IS_EGYPT', 'REQUIREMENTSET_TEST_ALL'),
('REQUIREMENTS_EGYPT_PLOT_HAS_RESOURCE', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
-- ('EGYPT_REQUIREMENTS', 'REQUIRES_PLAYER_HAS_FOREIGN_TRADE'),
('REQUIREMENTS_PLAYER_IS_EGYPT', 'PLAYER_IS_EGYPT'),
('REQUIREMENTS_EGYPT_PLOT_HAS_RESOURCE', 'PLAYER_IS_EGYPT'),
('REQUIREMENTS_EGYPT_PLOT_HAS_RESOURCE', 'PLOT_HAS_RESOURCE');

--Irrigation and Masonry's boost can unlock itself
-- INSERT INTO Requirements (RequirementId, RequirementType) VALUES 
-- ('PLAYER_HAS_RICE_IMPROVED', 'REQUIREMENT_PLAYER_HAS_RESOURCE_IMPROVED'), 
-- ('PLAYER_HAS_STONE_IMPROVED', 'REQUIREMENT_PLAYER_HAS_RESOURCE_IMPROVED'), 
-- ('PLAYER_HAS_WHEAT_IMPROVED', 'REQUIREMENT_PLAYER_HAS_RESOURCE_IMPROVED'), 
-- ('PLAYER_HAS_MAIZE_IMPROVED', 'REQUIREMENT_PLAYER_HAS_RESOURCE_IMPROVED');
-- INSERT INTO RequirementArguments (RequirementId, Name, Value) VALUES 
-- ('PLAYER_HAS_RICE_IMPROVED', 'ResourceType', 'RESOURCE_RICE'), 
-- ('PLAYER_HAS_STONE_IMPROVED', 'ResourceType', 'RESOURCE_STONE'), 
-- ('PLAYER_HAS_WHEAT_IMPROVED', 'ResourceType', 'resource_wheat'), 
-- ('PLAYER_HAS_MAIZE_IMPROVED', 'ResourceType', 'resource_maize');
-- INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
-- ('FARM_RESOURCE_IMPROVED', 'PLAYER_HAS_RICE_IMPROVED'),
-- ('FARM_RESOURCE_IMPROVED', 'PLAYER_HAS_RICE_IMPROVED'),
-- ('FARM_RESOURCE_IMPROVED', 'PLAYER_HAS_RICE_IMPROVED');
-- INSERT INTO RequirementSets (RequirementSetId, RequirementSetTpye) VALUES
-- ('FARM_RESOURCE_IMPROVED', 'REQUIREMENTSET_TEST_ALL');


UPDATE Improvements SET Description = 'LOC_IMPROVEMENT_SPHINX_DESCRIPTION_ZJ' WHERE ImprovementType = 'IMPROVEMENT_SPHINX';
UPDATE Traits SET Description = 'LOC_TRAIT_CIVILIZATION_ITERU_EXPANSION2_DESCRIPTION_ZJ' WHERE TraitType = 'TRAIT_CIVILIZATION_ITERU';
