UPDATE Districts SET Description = 'LOC_DISTRICT_LAVRA_DESCRIPTION_ZJ' WHERE DistrictType = 'DISTRICT_LAVRA';

DELETE FROM TraitModifiers WHERE ModifierId = 'TRAIT_TIER3_MUSICIAN_POINTS';

UPDATE Modifiers SET SubjectRequirementSetId = 'REQUIREMENTS_CITY_HAS_TEMPLE' WHERE ModifierId = 'TRAIT_SHRINE_WRITING_POINTS';
UPDATE Modifiers SET SubjectRequirementSetId = 'REQUIREMENTS_CITY_HAS_TIER3RELIGIOUS' WHERE ModifierId = 'TRAIT_TEMPLE_ARTIST_POINTS';